day_miles = float(input('How many miles do you drive a day>'))
gasmile= float(input('Whats the gas mileage of your car (miles per gallon)>'))
energy = float(input('What was the price of your energy bill last month (dollars)>'))
print('How often do you eat meat and dairy')
print('3. I have meat and dairy in alomst every meal')
print('2. I occatioaly eat meat and dairy')
print('1. I rearly every or never eat meat and dairy')
food = float(input())
furniture = float(input('Roughly how many new pieces of funiture did you buy in the past year (couches, beds, coffee tables, ...etc>'))
print('How much clothing do you have?')
print('3. I am a horder of clothes')
print('2. I have about a months worth of outfits in my closet')
print('1. I have very little clothes')
clothes = float(input())
gas = float(input('What was your natural gas bill last month (dollars)>'))
gas_p = (gas*(1000/6.65)*6.0406*.00001)*12
gass_p=(0.01*365*day_miles/gasmile)
energy_p = (energy*.92/(.12*2000))*12
food_p = (.35*(food-1))
furniture_p = (furniture*0.0881849)+.5+clothes*.5
total = gas_p+gass_p+energy_p+food_p
total = total + furniture_p
print(f'Your carbon footprint is {total:.2f} tons per year')


import turtle
import random
import time


stacy = turtle.Turtle()
stacy.hideturtle()
stacy.speed(0)
stacy.penup()
stacy.setpos(-200,-300)
stacy.pendown()
window = turtle.Screen()
window.setup(1000,1000)
window.bgcolor('light blue')
stacy.color('black')
stacy.forward(500)
stacy.setpos(-200,-300)
stacy.setheading(90)
stacy.forward(600)
stacy.penup()
stacy.setpos(80,-320)
stacy.write('gasoline                               food                    manufactured goods                   natural gas and energy', font=('Cambria',10,'italic'), align='center')
stacy.setpos(-300,0)
stacy.write('tons per year', font=('Cambria',20,'italic'), align='center')
 
stacy.setpos(-220,250)
stacy.write('8', font=('Cambria',20,'bold'), align='left')
stacy.setpos(-220,180)
stacy.write('7', font=('Cambria',20,'bold'), align='left')
stacy.setpos(-220,110)
stacy.write('6', font=('Cambria',20,'bold'), align='left')
stacy.setpos(-220,40)
stacy.write('5', font=('Cambria',20,'bold'), align='left')
stacy.setpos(-220,-30)
stacy.write('4', font=('Cambria',20,'bold'), align='left')
stacy.setpos(-220,-100)
stacy.write('3', font=('Cambria',20,'bold'), align='left')
stacy.setpos(-220,-170)
stacy.write('2', font=('Cambria',20,'bold'), align='left')
stacy.setpos(-220,-240)
stacy.write('1', font=('Cambria',20,'bold'), align='left')

stacy.penup()
stacy.setpos(-200,-300)
stacy.fillcolor('red')
stacy.pendown()
stacy.begin_fill()
stacy.setheading(0)
stacy.forward(100)
stacy.setheading(90)
stacy.forward(70*gass_p)
stacy.setheading(180)
stacy.forward(100)
stacy.setheading(270)
stacy.forward(70*gass_p)
stacy.end_fill()

stacy.penup()
stacy.setpos(-80,-300)
stacy.fillcolor('blue')
stacy.pendown()
stacy.begin_fill()
stacy.setheading(0)
stacy.forward(100)
stacy.setheading(90)
stacy.forward(70*food_p)
stacy.setheading(180)
stacy.forward(100)
stacy.setheading(270)
stacy.forward(70*food_p)
stacy.end_fill()


stacy.penup()
stacy.setpos(60,-300)
stacy.fillcolor('green')
stacy.pendown()
stacy.begin_fill()
stacy.setheading(0)
stacy.forward(100)
stacy.setheading(90)
stacy.forward(70*furniture_p)
stacy.setheading(180)
stacy.forward(100)
stacy.setheading(270)
stacy.forward(furniture_p*70)
stacy.end_fill()

stacy.penup()
stacy.setpos(200,-300)
stacy.fillcolor('yellow')
stacy.pendown()
stacy.begin_fill()
stacy.setheading(0)
stacy.forward(100)
stacy.setheading(90)
stacy.forward(70*(gas_p+energy_p))
stacy.setheading(180)
stacy.forward(100)
stacy.setheading(270)
stacy.forward(70*(gas_p+energy_p))
stacy.end_fill()

stacy.penup()
stacy.setpos(0,-400)
stacy.write(f'Your carbon footprint is {total:.2f} tons per year', font=('Cambria',20,'italic'), align='center')



